#!/usr/bin/bash
clear

# edit /etc/pacman.conf file
nano /etc/pacman.conf

clear

# timezone
echo 'Example: Europe/Istanbul, Europe/Zurich, America/New_York'
read -p 'Timezone: ' time_zone
ln -sf /usr/share/zoneinfo/$time_zone /etc/localtime
hwclock --systohc

clear

# locale

read -p "Select locale [en/tr]: " localeset

if [ $localeset == "en" ];
then
    echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
    touch /etc/locale.conf
    echo "LANG=en_US.UTF-8" >> /etc/locale.conf
else
    echo "tr_TR.UTF-8 UTF-8" >> /etc/locale.gen
    locale-gen
    touch /etc/locale.conf
    echo "LANG=tr_TR.UTF-8" >> /etc/locale.conf
fi

clear

# host
read -p 'Hostname: ' host_name
echo $host_name >> /etc/hostname

echo '127.0.0.1       localhost' >> /etc/hosts
echo '::1             localhost' >> /etc/hosts
echo '127.0.1.1       '$host_name'.localdomain     '$host_name >> /etc/hosts

clear

# root password
echo 'Root password'
passwd
sleep 2

clear

# packages
pacman -Sy networkmanager networkmanager-dinit
sleep 2
clear

echo 'After restarting the computer, enter the command "sudo dinitctl enable NetworkManager ; sudo dinitctl start NetworkManager'
sleep 6
clear

# touchpad support
pacman -S xf86-input-libinput
sleep 2
clear

# NTFS filesystem support
pacman -S ntfs-3g
sleep 2
clear

# GRUB
pacman -S grub efibootmgr os-prober
sleep 2
clear

grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id='Artix Linux'
sleep 2
clear

grub-mkconfig -o /boot/grub/grub.cfg
sleep 2
clear

# useradd
read -p 'Username: ' user_name
useradd -m -g users -G wheel,storage,power,audio,video -s /bin/bash $user_name
clear

echo $user_name 'password'
passwd $user_name
sleep 2

# sudo privileges
EDITOR=nano visudo
clear
